
export const CAP_EVENT = "Event"
export const CAP_UPDATED = "Updated"
export const CAMEL_DESCRIPTION = "description"
export const CAMEL_CREATED_AT = "createdAt"
export const CAP_STATUS = "Status"
export const CAP_RATING = "Rating" 
export const CAP_PRICE = "Price"
export const CAP_ACTION = "Action"
export const CAMEL_IS_PUBLISHED = "isPublished"
export const CAMEL_AVERAGE_RATING = "averageRating"
export const CAMEL_COST_PER_SESSION = "costPerSession"